name: Review Content Updated

on:
  push:
    branches:
      - main  # Assuming main is your default branch

jobs:
  notify-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify about update
      run: |
        echo "Review content has been updated. Trigger any required actions manually or set up an automatic trigger to the private repository."
