name: Trigger Private Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_FOR_PRIVATE_REPO }}
          repository: abraxasio/axs-papers-site
          event-type: update-review-content
